let D=null,current=null,currentKey=null,currentIndex=-1,flatRecords=[],lookupCtx=null,gps=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const BASE_GROUPS=[
 ['Макет 1 · Местонахождение таксационного выдела',['PLV','KU','OZU','CkEk','CkKr','VNUM','ErV','ErCt']],
 ['Макет 2 · Проектируемые мероприятия',['M2PM1','M2Pr','M22','M23','M2Cp']],
 ['Макет 3 · Лесорастительные условия',['M3Pr','M3B','M3TL','M3TLU','M3G','M3KP','M3KPC']],
 ['Макет 4 · Захламлённость',['M4ZO','M4ZL','M4SS']],
 ['Макет 31 · Подрост',['PRkol','PRH','PRA','PRK1','PRP1','PRK2','PRP2','PRK3','PRP3']],
 ['Макет 32 · Подлесок',['PLG','PLP1','PLP2','PLP3']]
];
const CHILD_GROUPS={'Макет10':['IAR','KOEF','POR','LET','PH','PD2','KT','PROI','POL','SPS','ZAP'],'Макет11':['GC','COP','CCZ','RMR','RVR','KOL','CLK','PG'],'Макет12':['KTP','GP','PORP','VV','SV','VB','SB','SP'],'Макет13':['SHT','PRT','SOST','NAZ','TP','SHR','SEZ','TM'],'Макет15':['KMP','G15','P15','VZ','AV','OC','PNV','PL15'],'Макет17':['PL','KU','TSP','CSP','P17','PR','UR'],'Макет19':['TB','TR','MTC','ZP','ZPR'],'Макет21':['TL','OES','ORE','UST','STP','SPR','SD','MAF'],'Макет23':['K1','K2','K3','K4','K5','K6','K7','K8'],'Макет27':['KU','KU_St']};
async function boot(){D=await fetch('./data.json').then(r=>r.json());$('#qcount').textContent=D.stats.quartersDistinct;$('#vcount').textContent=D.stats.compartments;$('#area').textContent=D.stats.area.toLocaleString('ru-RU');$('#rcount').textContent=D.stats.referenceTables;$('#rrows').textContent=D.stats.referenceRows.toLocaleString('ru-RU');flatRecords=[];Object.values(D.quarters).forEach(q=>q.compartments.forEach(r=>flatRecords.push(r)));renderQuarters();renderRefs();renderQuick();renderAllTables()}
function esc(v){if(v===null||v===undefined||v==='')return '—';return String(v).replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]))}
function fmtNum(v,d=1){if(v===null||v===undefined||v==='')return '—';const n=Number(v);return Number.isNaN(n)?esc(v):n.toLocaleString('ru-RU',{maximumFractionDigits:d})}
function show(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.s===id));scrollTo({top:0,behavior:'smooth'})}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1700)}
function label(k){return D.fieldLabels?.[k]||k} function lookupMap(k){return D.fieldLookups?.[k]||null} function decoded(k,v){const m=lookupMap(k);return m&&m[String(v)]!=null?m[String(v)]:''} function landName(v){return decoded('KU',v)}
function storageKey(r){return `solin:${r.POS}:${r.LESN}:${r.KV}:${r.KGLF}:${r.VD}`} function getWorking(r){try{const s=localStorage.getItem(storageKey(r));return s?{...r,...JSON.parse(s)}:{...r}}catch{return {...r}}}
function renderQuarters(filter=''){const box=$('#quarters');box.innerHTML='';Object.keys(D.quarters).sort((a,b)=>+a-+b).forEach(k=>{if(filter&&!String(k).includes(filter.trim()))return;const q=D.quarters[k],a=q.compartments.reduce((s,r)=>s+(+r.PLV||0),0);const e=document.createElement('div');e.className='panel quarterPanel';e.innerHTML=`<div class="qhead"><span class="code">${k}</span><div class="grow"><b>Квартал ${k}</b><small>${q.compartments.length} выделов · ${fmtNum(a)} га</small></div><button class="btn2">Открыть</button></div><div class="comp hidden"></div>`;const c=e.querySelector('.comp'),b=e.querySelector('button');b.onclick=()=>{c.classList.toggle('hidden');b.textContent=c.classList.contains('hidden')?'Открыть':'Скрыть';if(!c.dataset.done){c.dataset.done='1';renderCompList(c,q.compartments)}};box.appendChild(e)})}
function renderCompList(box,rs){box.innerHTML='';rs.forEach(r=>{const w=getWorking(r),card=document.createElement('button');card.className='compCard';card.innerHTML=`<span class="compNo">${esc(w.VD)}</span><span class="compText"><b>${esc(landName(w.KU)||'Категория '+(w.KU??'—'))}</b><small>${fmtNum(w.PLV)} га${w.Vsost?' · '+esc(w.Vsost):''}</small></span><span class="openArrow">›</span>`;card.onclick=()=>openRecord(r);box.appendChild(card)})}
function openRecord(raw){current=getWorking(raw);currentKey=storageKey(raw);currentIndex=flatRecords.findIndex(x=>storageKey(x)===currentKey);renderComp();show('card')}
function renderComp(){$('#cardTitle').textContent=`Квартал ${current.KV} · выдел ${current.VD}`;$('#cardSub').textContent=`${landName(current.KU)||'Категория '+(current.KU??'—')} · ${fmtNum(current.PLV)} га`;$('#recordPos').textContent=`${currentIndex+1} / ${flatRecords.length}`;const children=current._children||{},names=Object.keys(children).sort((a,b)=>a.localeCompare(b,'ru'));$('#childTabs').innerHTML=`<button class="tab active" data-name="_main">Макеты 1–5,31,32</button>`+names.map(n=>`<button class="tab" data-name="${esc(n)}">${esc(n)}</button>`).join('')+`<button class="tab" data-name="_tech">Технические поля</button>`;$$('#childTabs .tab').forEach(btn=>btn.onclick=()=>childTab(btn.dataset.name,btn));renderMainEdit();$('#childContent').innerHTML=''}
function renderMainEdit(){$('#editContent').innerHTML=BASE_GROUPS.map(([t,ks])=>editableSection(t,ks,current)).join('')} function editableSection(title,keys,obj){return `<div class="editSection"><h3>${esc(title)}</h3><div class="editGrid">${keys.map(k=>editField(k,obj)).join('')}</div></div>`}
function editField(k,obj){const v=obj[k]??'',m=lookupMap(k),name=decoded(k,v);if(m)return `<label class="editField"><span>${esc(label(k))}</span><div class="codeInput"><input data-field="${esc(k)}" value="${esc(v)}" onchange="changeField('${esc(k)}',this.value)"><button type="button" onclick="openLookup('${esc(k)}')">…</button></div><small class="decode" id="decode-${cssSafe(k)}">${esc(name||'Выбрать из справочника')}</small></label>`;return `<label class="editField"><span>${esc(label(k))}</span><input data-field="${esc(k)}" value="${esc(v)}" onchange="changeField('${esc(k)}',this.value)"></label>`}
function cssSafe(s){return String(s).replace(/[^a-z0-9_-]/gi,'_')} function changeField(k,v){const old=current[k];if(typeof old==='number'&&v!==''){const n=Number(v);current[k]=Number.isNaN(n)?v:n}else current[k]=v;const d=$(`#decode-${cssSafe(k)}`);if(d)d.textContent=decoded(k,current[k])||'Код не найден в связанном справочнике';if(k==='KU')$('#cardSub').textContent=`${landName(current.KU)||'Категория '+current.KU} · ${fmtNum(current.PLV)} га`}
function openLookup(k){const m=lookupMap(k);if(!m)return;lookupCtx={field:k,map:m};$('#lookupTitle').textContent=label(k);$('#lookupHint').textContent=`Шифр и наименование · ${Object.keys(m).length} значений`;$('#lookupSearch').value='';$('#lookupModal').classList.remove('hidden');renderLookup()} function renderLookup(){if(!lookupCtx)return;const q=$('#lookupSearch').value.trim().toLowerCase();const rows=Object.entries(lookupCtx.map).filter(([c,n])=>!q||String(c).toLowerCase().includes(q)||String(n).toLowerCase().includes(q));$('#lookupRows').innerHTML=rows.map(([c,n])=>`<button class="lookupRow" onclick="pickLookup('${String(c).replace(/'/g,"\\'")}')"><span class="code">${esc(c)}</span><span>${esc(n)}</span></button>`).join('')||'<div class="empty">Нет совпадений</div>'}
function pickLookup(code){const k=lookupCtx.field;current[k]=isNaN(Number(code))?code:Number(code);closeLookup();renderMainEdit();toast(`${label(k)}: ${decoded(k,current[k])||current[k]}`)} function closeLookup(){$('#lookupModal').classList.add('hidden');lookupCtx=null} function saveCurrent(){const copy={};Object.entries(current).forEach(([k,v])=>{if(k!=='_children')copy[k]=v});localStorage.setItem(currentKey,JSON.stringify(copy));toast('Карточка сохранена на устройстве')} function prevRecord(){if(currentIndex>0)openRecord(flatRecords[currentIndex-1])} function nextRecord(){if(currentIndex<flatRecords.length-1)openRecord(flatRecords[currentIndex+1])}
function childTab(name,btn){$$('#childTabs .tab').forEach(x=>x.classList.remove('active'));btn.classList.add('active');if(name==='_main'){renderMainEdit();$('#childContent').innerHTML='';return}$('#editContent').innerHTML='';if(name==='_tech'){$('#childContent').innerHTML=`<div class="editSection"><h3>Технические поля MDB</h3>${renderTech(current)}</div>`;return}const rs=(current._children||{})[name]||[];$('#childContent').innerHTML=`<div class="editSection"><h3>${esc(name)}</h3>${rs.map((r,i)=>renderChild(name,r,i)).join('')}</div>`} function renderChild(name,r,i){const keys=CHILD_GROUPS[name]||Object.keys(r).filter(k=>!['POS','LESN','KV','KGLF','VD'].includes(k));return `<div class="childBlock"><div class="childCaption">Запись ${i+1}</div><div class="editGrid">${keys.map(k=>readField(k,r[k])).join('')}</div></div>`} function readField(k,v){return `<div class="editField readonly"><span>${esc(label(k))}</span><b>${esc(v??'—')}</b>${decoded(k,v)?`<small class="decode">${esc(decoded(k,v))}</small>`:''}</div>`} function renderTech(obj){return `<div class="techGrid">${Object.entries(obj).filter(([k])=>k!=='_children').map(([k,v])=>`<div class="techField"><span>${esc(k)}</span><b>${esc(v)}</b></div>`).join('')}</div>`}
function renderQuick(){const groups=[['Категории угодий','landUse'],['Породы','species'],['Ярусы','tiers'],['Бонитет','bonitet'],['Тип болота','bogType'],['Покрытие дороги','roadSurface']];$('#quickRefs').innerHTML=groups.map(([t,k])=>`<details class="refTable"><summary><b>${t}</b> · ${(D.quick[k]||[]).length}</summary><div class="refBody">${(D.quick[k]||[]).map(x=>`<div class="row"><span class="code">${esc(x.code)}</span><div class="grow">${esc(x.name)}</div></div>`).join('')}</div></details>`).join('')}
function renderRefs(query=''){query=query.trim().toLowerCase();let meta=D.referenceMeta;if(query)meta=meta.filter(m=>m.name.toLowerCase().includes(query)||m.columns.some(c=>String(c).toLowerCase().includes(query)));$('#refTables').innerHTML=meta.map(m=>`<details class="refTable"><summary data-n="${encodeURIComponent(m.name)}"><b>${esc(m.name)}</b> · ${m.rows} строк</summary><div class="refBody"><div class="empty">Нажми, чтобы открыть</div></div></details>`).join('');$$('#refTables summary').forEach(s=>s.onclick=()=>loadRef(decodeURIComponent(s.dataset.n),s))} function loadRef(n,s){const b=s.parentElement.querySelector('.refBody');if(b.dataset.done)return;b.dataset.done='1';const rs=D.references[n]||[],cs=D.referenceSchema[n]||[];b.innerHTML=rs.length?rs.map(r=>`<div class="refrow"><div class="refkey">${esc(bestCode(r,cs))}</div><div class="refval">${esc(bestText(r,cs))}</div></div>`).join(''):'<div class="empty">Пустой справочник</div>'} function bestCode(r,cs){let c=cs.find(c=>/^(K|KU|KOD|KTB|KM|KIAR|KPC|M3B)/i.test(c)&&r[c]!=null);return c?`${r[c]}`:(cs[0]?r[cs[0]]:'')} function bestText(r,cs){let c=cs.find(c=>/^(N|NKU|NTB|NDP|NM|NMR|NIAR|T)/i.test(c)&&typeof r[c]==='string'&&r[c].trim());if(c)return r[c];c=cs.find(c=>typeof r[c]==='string'&&r[c].trim());return c?r[c]:Object.values(r).filter(v=>v!=null).join(' · ')} function searchEveryRef(q){q=q.trim().toLowerCase();if(q.length<2){$('#refSearchResults').innerHTML='';return}let hits=[];for(const [t,rs] of Object.entries(D.references)){for(const r of rs){const s=Object.values(r).filter(v=>v!=null&&typeof v!=='object').join(' ').toLowerCase();if(s.includes(q)){hits.push([t,r]);if(hits.length>=150)break}}if(hits.length>=150)break}$('#refSearchResults').innerHTML=hits.length?`<div class="sectionTitle">Найдено: ${hits.length}</div>`+hits.map(([t,r])=>`<div class="row"><span class="code">${esc(t)}</span><div class="grow"><b>${esc(bestText(r,D.referenceSchema[t]||[]))}</b><br><small>${esc(bestCode(r,D.referenceSchema[t]||[]))}</small></div></div>`).join(''):'<div class="empty">Совпадений нет</div>'}
function renderAllTables(){$('#dbTables').innerHTML=Object.entries(D.transfTables).sort().map(([n,rs])=>`<div class="row"><span class="code">${esc(n)}</span><div class="grow"><b>${rs.length} строк</b><br><small>${(D.transfSchema[n]||[]).join(', ')}</small></div></div>`).join('')} function locate(){if(!navigator.geolocation){toast('GPS недоступен');return}$('#gpsText').textContent='Определяю…';navigator.geolocation.getCurrentPosition(p=>{gps={lat:p.coords.latitude,lon:p.coords.longitude,acc:p.coords.accuracy};$('#gpsText').textContent=`${gps.lat.toFixed(6)}, ${gps.lon.toFixed(6)} · ±${Math.round(gps.acc)} м`;$('#gpsDot').style.background='#6ed67d';toast('GPS обновлён')},()=>toast('Разреши геолокацию'),{enableHighAccuracy:true,timeout:10000})}
window.addEventListener('DOMContentLoaded',boot);if('serviceWorker'in navigator){navigator.serviceWorker.register('./sw.js').catch(()=>{})}