let D=null,current=null,gps=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const aliases={M3Pr:'POR',M2Cp:'POR',PRP1:'POR',PRP2:'POR',PRP3:'POR',PLP1:'POR',PLP2:'POR',PLP3:'POR',PORP:'POR',P15:'POR',M22:'M2PM1',M23:'M2PM1'};
async function getJSON(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(url+' '+r.status);return r.json()}
async function boot(){
 try{
  const mf=await getJSON('./data-manifest.json');
  D=await getJSON('./data-meta.json');
  const chunks=await Promise.all(mf.quarterChunks.map(f=>getJSON('./'+f)));
  D.quarters=Object.assign({},...chunks);D.references=D.references||{};
  $('#qcount').textContent=Object.keys(D.quarters).length;
  $('#vcount').textContent=Object.values(D.quarters).reduce((n,q)=>n+q.compartments.length,0);
  $('#area').textContent=D.stats.area.toLocaleString('ru-RU')+' га';
  $('#rcount').textContent=D.stats.referenceTables;$('#rrows').textContent=D.stats.referenceRows.toLocaleString('ru-RU');
  renderQuarters();renderRefs();renderQuick();renderAllTables();
 }catch(e){console.error(e);toast('Ошибка загрузки данных');const h=$('#quickRefs');if(h)h.innerHTML='<div class="empty danger">Не удалось загрузить данные. Обнови страницу.</div>'}
}
function esc(v){if(v===null||v===undefined||v==='')return '—';return String(v).replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function fmtNum(v,d=1){if(v===null||v===undefined||v==='')return '—';const n=Number(v);return Number.isNaN(n)?esc(v):n.toLocaleString('ru-RU',{maximumFractionDigits:d})}
function show(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id)?.classList.add('active');$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.s===id));scrollTo({top:0,behavior:'smooth'})}
function toast(t){const e=$('#toast');if(!e)return;e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1700)}
function label(k){return D?.fieldLabels?.[k]||k}
function lookup(k){return D?.fieldLookups?.[k]||D?.fieldLookups?.[aliases[k]]}
function decodeField(k,v){if(v===null||v===undefined||v==='')return '—';const m=lookup(k);return m&&m[String(v)]!=null?`${m[String(v)]} · шифр ${v}`:v}
function landName(v){return D?.fieldLookups?.KU?.[String(v)]||''}
function speciesName(v){return D?.fieldLookups?.POR?.[String(v)]||''}
function renderQuarters(filter=''){
 const box=$('#quarters');box.innerHTML='';
 Object.keys(D.quarters).sort((a,b)=>+a-+b).forEach(k=>{if(filter&&!k.includes(filter.trim()))return;const q=D.quarters[k],a=q.compartments.reduce((s,r)=>s+(+r.PLV||0),0);const el=document.createElement('div');el.className='panel';el.innerHTML=`<div class="qhead"><span class="code">КВ ${k}</span><div class="grow"><h3>Квартал ${k}</h3><div class="qmeta">${q.compartments.length} выделов · ${fmtNum(a)} га</div></div><button class="btn2">Показать выделы</button></div><div class="comp hidden"></div>`;const c=el.querySelector('.comp'),b=el.querySelector('button');b.onclick=()=>{c.classList.toggle('hidden');b.textContent=c.classList.contains('hidden')?'Показать выделы':'Скрыть';if(!c.dataset.done){c.dataset.done=1;renderCompList(c,q.compartments)}};box.appendChild(el)})
}
function renderCompList(box,rs){box.innerHTML='';rs.forEach(r=>{const card=document.createElement('button');card.className='compCard';const cat=landName(r.KU)||`Категория угодий ${r.KU??'—'}`,comp=(r.Vsost||'').trim(),sp=comp||(r.M3Pr?speciesName(r.M3Pr)||r.M3Pr:'');card.innerHTML=`<span class="compNo">№ ${esc(r.VD)}</span><span class="compText"><b>${esc(cat)}</b><small>${fmtNum(r.PLV)} га${sp?' · '+esc(sp):''}</small></span><span class="openArrow">›</span>`;card.onclick=()=>{current=r;renderComp();show('card')};box.appendChild(card)})}
function section(title,keys,obj){const items=keys.filter(k=>obj[k]!==null&&obj[k]!==undefined&&obj[k]!=='');if(!items.length)return '';return `<div class="humanSection"><h3>${esc(title)}</h3><div class="humanGrid">${items.map(k=>`<div class="humanField"><span>${esc(label(k))}</span><b>${esc(decodeField(k,obj[k]))}</b></div>`).join('')}</div></div>`}
function renderComp(){
 $('#cardTitle').textContent=`Квартал ${current.KV} · выдел ${current.VD}`;$('#cardSub').textContent=`${landName(current.KU)||'Категория угодий '+(current.KU??'—')} · ${fmtNum(current.PLV)} га`;
 $('#humanContent').innerHTML=section('Основные сведения',['PLV','KU','OZU','CkEk','CkKr','VNUM','ErV','ErCt'],current)+section('Проектируемые мероприятия · Макет 2',['M2PM1','M2Pr','M22','M23','M2Cp'],current)+section('Лесорастительные условия · Макет 3',['M3Pr','M3B','M3TL','M3TLU','M3G','M3KP','M3KPC'],current)+section('Захламлённость · Макет 4',['M4ZO','M4ZL','M4SS'],current)+section('Подрост · Макет 31',['PRkol','PRH','PRA','PRK1','PRP1','PRK2','PRP2','PRK3','PRP3'],current)+section('Подлесок · Макет 32',['PLG','PLP1','PLP2','PLP3'],current);
 const names=Object.keys(current._children||{}).sort((a,b)=>a.localeCompare(b,'ru'));$('#childTabs').innerHTML=`<button class="tab active" data-name="_main">Карточка</button>`+names.map(n=>`<button class="tab" data-name="${esc(n)}">${esc(n)}</button>`).join('')+`<button class="tab" data-name="_tech">Технические поля</button>`;$$('#childTabs .tab').forEach(btn=>btn.onclick=()=>childTab(btn.dataset.name,btn));$('#childContent').innerHTML=''
}
function childTab(name,btn){$$('#childTabs .tab').forEach(x=>x.classList.remove('active'));btn.classList.add('active');if(name==='_main'){$('#childContent').innerHTML='';return}if(name==='_tech'){$('#childContent').innerHTML=`<div class="sectionTitle">Технические поля MDB</div>${renderTech(current)}`;return}const rs=(current._children||{})[name]||[];$('#childContent').innerHTML=`<div class="sectionTitle">${esc(name)}</div>`+rs.map(r=>renderChildReadable(name,r)).join('')}
function renderChildReadable(name,r){if(name==='Макет10')return `<div class="childBlock">${section('Таксационная характеристика древостоя',['IAR','KOEF','POR','LET','PH','PD2','KT','PROI','POL','SPS','ZAP'],r)}</div>`;if(name==='Макет19')return `<div class="childBlock">${section('Болото',['TB','TR','MTC','ZP','ZPR'],r)}</div>`;return `<div class="childBlock">${renderReadableGeneric(r)}</div>`}
function renderReadableGeneric(r){const es=Object.entries(r).filter(([k,v])=>!['POS','LESN','KV','KGLF','VD'].includes(k)&&v!==null&&v!==undefined&&v!=='');return es.length?`<div class="humanGrid">${es.map(([k,v])=>`<div class="humanField"><span>${esc(label(k))}</span><b>${esc(decodeField(k,v))}</b></div>`).join('')}</div>`:'<div class="empty">Нет заполненных показателей</div>'}
function renderTech(obj){return `<div class="techGrid">${Object.entries(obj).filter(([k])=>k!=='_children').map(([k,v])=>`<div class="techField"><span>${esc(k)}</span><b>${esc(typeof v==='object'?JSON.stringify(v):v)}</b></div>`).join('')}</div>`}
function rowsFromLookup(k){return Object.entries(D.fieldLookups?.[k]||{}).filter(([c,n])=>c!==''&&n!==null&&n!=='').map(([code,name])=>({code,name}))}
function renderQuick(){const groups=[['Категории угодий · SKU',rowsFromLookup('KU')],['Древесные и кустарниковые породы · SDP',rowsFromLookup('POR')],['Ярусы · SIAR',rowsFromLookup('IAR')],['Бонитет · SBon',rowsFromLookup('M3B')],['Тип болота · STB',rowsFromLookup('TB')]];$('#quickRefs').innerHTML=groups.map(([t,arr])=>`<details class="refTable"><summary><b>${t}</b> · ${arr.length}</summary><div class="refBody">${arr.map(x=>`<div class="row"><span class="code">${esc(x.code)}</span><div class="grow">${esc(x.name)}</div></div>`).join('')}</div></details>`).join('')}
function renderRefs(query=''){query=query.trim().toLowerCase();let meta=D.referenceMeta||[];if(query)meta=meta.filter(m=>m.name.toLowerCase().includes(query)||(m.columns||[]).some(c=>String(c).toLowerCase().includes(query)));$('#refTables').innerHTML=meta.map(m=>`<details class="refTable"><summary data-n="${encodeURIComponent(m.name)}"><b>${esc(m.name)}</b> · ${m.rows} строк</summary><div class="refBody"><div class="empty">Открыть справочник</div></div></details>`).join('');$$('#refTables summary').forEach(s=>s.onclick=()=>loadRef(decodeURIComponent(s.dataset.n),s))}
async function loadRef(n,s){const b=s.parentElement.querySelector('.refBody');if(b.dataset.done)return;b.dataset.done=1;let rs=D.references[n];if(!rs){try{rs=await getJSON('./refs/'+encodeURIComponent(n)+'.json');D.references[n]=rs}catch(e){b.innerHTML='<div class="empty">Этот справочник ещё переносится в живую сборку</div>';return}}const cs=D.referenceSchema?.[n]||[];b.innerHTML=rs.length?rs.map(r=>`<div class="refrow"><div class="refkey">${esc(bestCode(r,cs))}</div><div class="refval">${esc(bestText(r,cs))}</div></div>`).join(''):'<div class="empty">Пустой справочник</div>'}
function bestCode(r,cs){const c=cs.find(c=>/^(K|KU|KOD|KTB|KM|KIAR|KPC|M3B)/i.test(c)&&r[c]!=null);return c?String(r[c]):(cs[0]?r[cs[0]]:'')}
function bestText(r,cs){let c=cs.find(c=>/^(N|NKU|NTB|NDP|NM|NIAR|T)/i.test(c)&&typeof r[c]==='string'&&r[c].trim());if(c)return r[c];c=cs.find(c=>typeof r[c]==='string'&&r[c].trim());return c?r[c]:Object.values(r).filter(v=>v!=null).join(' · ')}
function searchEveryRef(q){q=q.trim().toLowerCase();if(q.length<2){$('#refSearchResults').innerHTML='';return}let hits=[];for(const[t,rs]of Object.entries(D.references)){for(const r of rs){if(Object.values(r).join(' ').toLowerCase().includes(q)){hits.push([t,r]);if(hits.length>=100)break}}}$('#refSearchResults').innerHTML=hits.length?`<div class="sectionTitle">Найдено: ${hits.length}</div>`+hits.map(([t,r])=>`<div class="row"><span class="code">${esc(t)}</span><div class="grow"><b>${esc(bestText(r,D.referenceSchema?.[t]||[]))}</b></div></div>`).join(''):'<div class="empty">Совпадений среди загруженных справочников нет</div>'}
function renderAllTables(){$('#dbTables').innerHTML=Object.entries(D.transfSchema||{}).map(([n,cols])=>`<div class="row"><span class="code">${esc(n)}</span><div class="grow"><b>${cols.length} полей</b><br><small>${cols.join(', ')}</small></div></div>`).join('')}
function locate(){if(!navigator.geolocation){toast('GPS недоступен');return}$('#gpsText').textContent='Определяю координаты…';navigator.geolocation.getCurrentPosition(p=>{gps={lat:p.coords.latitude,lon:p.coords.longitude,acc:p.coords.accuracy};$('#gpsText').textContent=`${gps.lat.toFixed(6)}, ${gps.lon.toFixed(6)} · ±${Math.round(gps.acc)} м`;$('#gpsDot').style.background='#78e68b';toast('GPS-точка обновлена')},()=>toast('Разреши геолокацию'),{enableHighAccuracy:true,timeout:10000})}
window.addEventListener('DOMContentLoaded',boot);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(console.warn);