/* CMF2 post-processing: PageStorage FTS4 attributes + per-file alignment. */
(function(){
 const FTS_COL={FID:1,'КатЗащ':2,'КатЗем':3,'Ключ':4,'Лесничеств':5,'Порода':6,'ПородаПП':7,'Тип_леса':8,'ХозРаспор1':9,'ХозРаспор2':10};
 let sqlPromise=null;
 function rows(res){if(!res?.length)return[];const c=res[0].columns;return res[0].values.map(v=>Object.fromEntries(c.map((k,i)=>[k,v[i]])))}
 function be16(b,o){return(b[o]<<8)|b[o+1]}
 function be32(b,o){return((b[o]<<24)|(b[o+1]<<16)|(b[o+2]<<8)|b[o+3])>>>0}
 function safeTerm(s){return String(s).replace(/[^0-9A-Za-zА-Яа-яЁё_\-]/g,'')}
 async function sql(){if(window.SQL?.Database)return window.SQL;if(!window.initSqlJs)return null;if(!sqlPromise)sqlPromise=window.initSqlJs({locateFile:f=>'https://unpkg.com/sql.js@1.10.3/dist/'+f});return sqlPromise}
 function fileKey(file){return `cmf-align|${file.name}|${file.size}|${file.lastModified}`}
 function savedAlign(file){try{return JSON.parse(localStorage.getItem(fileKey(file))||'{"east":0,"north":0}')}catch(_){return{east:0,north:0}}}
 function shiftCoord(c,east,north){if(!Array.isArray(c))return c;if(typeof c[0]==='number'&&typeof c[1]==='number'){const lat=c[1],dLat=north/111320,dLon=east/(111320*Math.cos(lat*Math.PI/180));return[c[0]+dLon,c[1]+dLat,...c.slice(2)]}return c.map(x=>shiftCoord(x,east,north))}
 function shiftInfo(info,east,north){if(!east&&!north)return info;for(const g of info.geometryLayers||[])for(const f of g.geojson?.features||[])if(f.geometry?.coordinates)f.geometry.coordinates=shiftCoord(f.geometry.coordinates,east,north);info.carryAlignment={east,north,method:'saved visual calibration'};return info}
 function lzPage(raw,start,maxOut){const r=window.SolinCmf2Lz4?.decodeRaw?.(raw,start,maxOut);return r&&r.bytes?.length?r:null}
 function plausiblePage(b){return b?.length>=16&&(b[0]===2||b[0]===5||b[0]===10||b[0]===13)}
 function rebuildPageStorage(raw,blockOffset){const firstStart=blockOffset+13,first=lzPage(raw,firstStart,70000);if(!first||first.bytes.length<100||String.fromCharCode(...first.bytes.slice(0,15))!=='SQLite format 3')return null;let pageSize=be16(first.bytes,16);if(pageSize===1)pageSize=65536;const pageCount=be32(first.bytes,28);if(!pageSize||!pageCount||pageCount>4096||first.bytes.length<pageSize)return null;const pages=[first.bytes.slice(0,pageSize)];let cursor=first.inputEnd;for(let p=1;p<pageCount;p++){let best=null;for(let s=Math.max(firstStart,cursor-12);s<=Math.min(raw.length-1,cursor+12);s++){const q=lzPage(raw,s,pageSize+16);if(!q||q.bytes.length<pageSize||!plausiblePage(q.bytes))continue;const score=Math.abs(s-cursor);if(!best||score<best.score)best={score,start:s,q}}if(!best)return null;pages.push(best.q.bytes.slice(0,pageSize));cursor=best.q.inputEnd}const out=new Uint8Array(pageSize*pageCount);pages.forEach((p,i)=>out.set(p,i*pageSize));return out}
 function ringAreaHa(r){if(!Array.isArray(r)||r.length<3)return 0;const lat0=r.reduce((s,p)=>s+p[1],0)/r.length,ky=111320,kx=111320*Math.cos(lat0*Math.PI/180);let a=0;for(let i=0;i<r.length;i++){const p=r[i],q=r[(i+1)%r.length];a+=(p[0]*kx)*(q[1]*ky)-(q[0]*kx)*(p[1]*ky)}return Math.abs(a)/2/10000}
 function geomAreaHa(g){if(!g)return null;if(g.type==='Polygon')return g.coordinates.reduce((s,r,i)=>s+(i?-1:1)*ringAreaHa(r),0);if(g.type==='MultiPolygon')return g.coordinates.reduce((s,p)=>s+p.reduce((z,r,i)=>z+(i?-1:1)*ringAreaHa(r),0),0);return null}
 function decodeNumericKeyPairs(db,docs){let keyTerms=[];try{keyTerms=rows(db.exec(`select term, documents from cmf_aux where col=${FTS_COL['Ключ']}`)).filter(x=>/^\d+$/.test(String(x.term)))}catch(_){return}const freq=new Map(keyTerms.map(x=>[String(x.term),Number(x.documents)||9999]));const perDoc=Array.from({length:docs.length},()=>[]);for(const x of keyTerms){const t=String(x.term);let rr=[];try{rr=rows(db.exec(`select docid from idx where idx match 'Ключ:${t}'`))}catch(_){continue}for(const r of rr){const d=Number(r.docid);if(d>=0&&d<perDoc.length)perDoc[d].push(t)}}for(let d=0;d<perDoc.length;d++){const ts=[...new Set(perDoc[d])];if(ts.length<2)continue;ts.sort((a,b)=>(freq.get(a)||9999)-(freq.get(b)||9999)||Number(b)-Number(a));const q=ts[0],v=ts[1];docs[d].Nкварт=Number(q);docs[d].Nвыд=Number(v);docs[d]['Ключ']=`${q}_${v}`}}
 async function indexedAttrs(file,info){const stand=(info.geometryLayers||[]).find(g=>/выдпород|выдел/i.test(g.source||''));const block=(info?.blocks||[]).find(b=>b.layer===stand?.source)||(info?.blocks||[])[stand?.index??0]||(info?.blocks||[])[0];if(block?.offset==null)return null;const raw=new Uint8Array(await file.arrayBuffer()),dbBytes=rebuildPageStorage(raw,block.offset);if(!dbBytes)return null;const S=await sql();if(!S)return null;let db;try{db=new S.Database(dbBytes);try{db.run('CREATE VIRTUAL TABLE cmf_aux USING fts4aux(idx)')}catch(_){return null}const wanted=['FID','Лесничеств','Порода','Тип_леса','КатЗем','КатЗащ','ХозРаспор1','ХозРаспор2'];const docs=Array.from({length:stand?.count||0},()=>({}));for(const col of wanted){const ci=FTS_COL[col],terms=rows(db.exec(`select term from cmf_aux where col=${ci}`)).map(x=>String(x.term));for(const term of terms){const t=safeTerm(term);if(!t)continue;let rr=[];try{rr=rows(db.exec(`select docid from idx where idx match '${col}:${t.replace(/'/g,"''")}'`))}catch(_){continue}for(const x of rr){const d=Number(x.docid);if(d<0||d>=docs.length)continue;if(docs[d][col]==null)docs[d][col]=term;else if(docs[d][col]!==term)docs[d][col]+=' '+term}}}decodeNumericKeyPairs(db,docs);return docs}finally{try{db?.close()}catch(_){}}}
 function applyAttrs(info,docs){const stand=(info.geometryLayers||[]).find(g=>/выдпород|выдел/i.test(g.source||''));if(!stand)return;for(let i=0;i<stand.geojson.features.length;i++){const f=stand.geojson.features[i],a=docs?.[i]||{};Object.assign(f.properties,a);if(a.Nкварт!=null)f.properties.Nкварт=a.Nкварт;if(a.Nвыд!=null)f.properties.Nвыд=a.Nвыд;if(a['Лесничеств'])f.properties['Лесничество']=a['Лесничеств'].charAt(0).toUpperCase()+a['Лесничеств'].slice(1);const ar=geomAreaHa(f.geometry);if(Number.isFinite(ar)){f.properties['Площ_геом']=Math.round(ar*10)/10;if(f.properties['Площ']==null)f.properties['Площ']=Math.round(ar*10)/10}}}
 async function prepare(file,info){const a=savedAlign(file);shiftInfo(info,Number(a.east)||0,Number(a.north)||0);try{applyAttrs(info,await indexedAttrs(file,info));info.attributesDecoded=true}catch(e){console.warn('CMF2 attributes',e);applyAttrs(info,null);info.attributesDecoded=false}info._cmfFileKey=fileKey(file);return info}
 function saveAlignmentByKey(key,east,north){try{localStorage.setItem(key,JSON.stringify({east,north}))}catch(_){} }
 const install=()=>{if(typeof window.inspectCmf2!=='function')return false;const original=window.inspectCmf2;if(original._cmfRuntimeWrapped)return true;const wrapped=async file=>prepare(file,await original(file));wrapped._cmfRuntimeWrapped=true;window.inspectCmf2=wrapped;return true};
 window.SolinCmfRuntime={prepare,indexedAttrs,rebuildPageStorage,shiftCoord,saveAlignmentByKey,savedAlign};
 if(!install())setTimeout(install,0);
})();