/* CMF2 post-processing: CarryMap alignment + indexed attribute recovery from embedded FTS4. */
(function(){
 const ALIGN={east:1276.37,north:-276.98};
 let sqlPromise=null;
 function isBuge(info){const e=info?.extent?.utm;if(!e)return false;return Math.abs(e.xmin-639747.4934281772)<2&&Math.abs(e.ymin-5528147.811550171)<2&&Math.abs(e.xmax-689706.7469352122)<2&&Math.abs(e.ymax-5580684.187923169)<2}
 function shiftCoord(c){if(!Array.isArray(c))return c;if(typeof c[0]==='number'&&typeof c[1]==='number'){const lat=c[1],dLat=ALIGN.north/111320,dLon=ALIGN.east/(111320*Math.cos(lat*Math.PI/180));return[c[0]+dLon,c[1]+dLat,...c.slice(2)]}return c.map(shiftCoord)}
 function shiftInfo(info){if(!isBuge(info)||info._carryAligned)return;for(const g of info.geometryLayers||[])for(const f of g.geojson?.features||[])if(f.geometry?.coordinates)f.geometry.coordinates=shiftCoord(f.geometry.coordinates);info._carryAligned=true;info.carryAlignment={...ALIGN,method:'control-point'};}
 function ringAreaHa(r){if(!Array.isArray(r)||r.length<3)return 0;const lat0=r.reduce((s,p)=>s+p[1],0)/r.length,ky=111320,kx=111320*Math.cos(lat0*Math.PI/180);let a=0;for(let i=0;i<r.length;i++){const p=r[i],q=r[(i+1)%r.length];a+=(p[0]*kx)*(q[1]*ky)-(q[0]*kx)*(p[1]*ky)}return Math.abs(a)/2/10000}
 function geomAreaHa(g){if(!g)return null;if(g.type==='Polygon')return g.coordinates.reduce((s,r,i)=>s+(i? -1:1)*ringAreaHa(r),0);if(g.type==='MultiPolygon')return g.coordinates.reduce((s,p)=>s+p.reduce((z,r,i)=>z+(i?-1:1)*ringAreaHa(r),0),0);return null}
 function be16(b,o){return(b[o]<<8)|b[o+1]}
 function be32(b,o){return((b[o]<<24)|(b[o+1]<<16)|(b[o+2]<<8)|b[o+3])>>>0}
 async function sql(){if(window.SQL?.Database)return window.SQL;if(!window.initSqlJs)return null;if(!sqlPromise)sqlPromise=window.initSqlJs({locateFile:f=>'https://unpkg.com/sql.js@1.10.3/dist/'+f});return sqlPromise}
 function rows(res){if(!res?.length)return[];const c=res[0].columns;return res[0].values.map(v=>Object.fromEntries(c.map((k,i)=>[k,v[i]])))}
 function safeMatchName(s){return String(s).replace(/[^0-9A-Za-zА-Яа-яЁё_$]/g,'')}
 async function indexedAttrs(file,info){const block=info?.blocks?.[0],off=block?.sqliteOffset;if(off==null)return null;const raw=new Uint8Array(await file.arrayBuffer());if(off+100>raw.length||String.fromCharCode(...raw.slice(off,off+6))!=='SQLite')return null;let ps=be16(raw,off+16);if(ps===1)ps=65536;const pages=be32(raw,off+28),size=ps*pages;if(!ps||!pages||off+size>raw.length)return null;const S=await sql();if(!S)return null;let db;try{db=new S.Database(raw.slice(off,off+size));const schema=rows(db.exec("select sql from sqlite_master where name='idx'"))[0]?.sql||'';const m=schema.match(/fts4\((.*)\)/i);if(!m)return null;const cols=[...m[1].matchAll(/\"([^\"]+)\"/g)].map(x=>x[1]);db.run('CREATE VIRTUAL TABLE cmf_aux USING fts4aux(idx)');const wanted=['FID','Ключ','Лесничеств','Порода','Тип_леса','КатЗем','КатЗащ','ХозРаспор1','ХозРаспор2'];const docs=Array.from({length:info.geometryLayers?.[0]?.count||0},()=>({}));for(const col of wanted){const ci=cols.indexOf(col);if(ci<0)continue;const terms=rows(db.exec(`select term from cmf_aux where col=${ci}`)).map(x=>String(x.term));const per=Array.from({length:docs.length},()=>[]);for(const term of terms){const q=`${safeMatchName(col)}:${term.replace(/[^0-9A-Za-zА-Яа-яЁё_\-]/g,'')}`;if(!q.split(':')[1])continue;let rr=[];try{rr=rows(db.exec(`select docid from idx where idx match '${q.replace(/'/g,"''")}'`))}catch(_){continue}for(const x of rr){const d=Number(x.docid);if(d>=0&&d<per.length)per[d].push(term)}}for(let d=0;d<per.length;d++){if(!per[d].length)continue;if(['FID','Ключ','Порода','Тип_леса','Лесничеств'].includes(col)||per[d].length===1)docs[d][col]=per[d].join(' ');else docs[d][col+'_tokens']=per[d].join(' ')}}
 return docs}finally{try{db?.close()}catch(_){}}}
 function applyAttrs(info,docs){const stand=(info.geometryLayers||[]).find(g=>/выдпород|выдел/i.test(g.source||''));if(!stand||!docs)return;for(let i=0;i<stand.geojson.features.length;i++){const f=stand.geojson.features[i],a=docs[i]||{};Object.assign(f.properties,a);const key=a['Ключ'];if(key&&/^\d+_\d+/.test(key)){const [q,v]=key.split('_');f.properties.Nкварт=Number(q);f.properties.Nвыд=Number(v)}if(a['Лесничеств'])f.properties['Лесничество']=a['Лесничеств'].charAt(0).toUpperCase()+a['Лесничеств'].slice(1);const ar=geomAreaHa(f.geometry);if(Number.isFinite(ar)){f.properties['Площ_геом']=Math.round(ar*10)/10;if(f.properties['Площ']==null)f.properties['Площ']=Math.round(ar*10)/10}}}
 async function prepare(file,info){shiftInfo(info);try{applyAttrs(info,await indexedAttrs(file,info))}catch(e){console.warn('CMF2 attributes',e)}return info}
 const install=()=>{if(typeof window.inspectCmf2!=='function')return false;const original=window.inspectCmf2;if(original._cmfRuntimeWrapped)return true;const wrapped=async file=>prepare(file,await original(file));wrapped._cmfRuntimeWrapped=true;window.inspectCmf2=wrapped;return true};
 window.SolinCmfRuntime={prepare,shiftInfo,indexedAttrs,alignment:ALIGN};
 if(!install())setTimeout(install,0);
})();