/* CMF2 structure reader: exact first SpatialBlock LZ4 boundary + PageStorage probing. No fabricated geometry. */
(function(){
 function asciiAt(u8,o,n){let s='';for(let i=o;i<Math.min(u8.length,o+n);i++)s+=String.fromCharCode(u8[i]);return s}
 function findAscii(u8,needle){const n=[...needle].map(c=>c.charCodeAt(0)),out=[];outer:for(let i=0;i<=u8.length-n.length;i++){for(let j=0;j<n.length;j++)if(u8[i+j]!==n[j])continue outer;out.push(i)}return out}
 function u32(u8,o){return o+4<=u8.length?(u8[o]|u8[o+1]<<8|u8[o+2]<<16|u8[o+3]<<24)>>>0:null}
 function utmToWgs84(easting,northing,zone,southHemisphere=false){const a=6378137,e2=.00669438,k0=.9996,ep=e2/(1-e2);if(southHemisphere)northing-=10000000;const M=northing/k0,mu=M/(a*(1-e2/4-3*e2*e2/64-5*Math.pow(e2,3)/256)),e1=(1-Math.sqrt(1-e2))/(1+Math.sqrt(1-e2)),p=mu+(3*e1/2-27*Math.pow(e1,3)/32)*Math.sin(2*mu)+(21*e1*e1/16-55*Math.pow(e1,4)/32)*Math.sin(4*mu)+(151*Math.pow(e1,3)/96)*Math.sin(6*mu),N=a/Math.sqrt(1-e2*Math.sin(p)**2),T=Math.tan(p)**2,C=ep*Math.cos(p)**2,R=a*(1-e2)/Math.pow(1-e2*Math.sin(p)**2,1.5),D=(easting-500000)/(N*k0),lat=p-(N*Math.tan(p)/R)*(D**2/2-(5+3*T+10*C-4*C*C-9*ep)*D**4/24+(61+90*T+298*C+45*T*T-252*ep-3*C*C)*D**6/720),lon=(D-(1+2*T+C)*D**3/6+(5-2*C+28*T-3*C*C+8*ep+24*T*T)*D**5/120)/Math.cos(p),origin=(zone-1)*6-180+3;return[lat*180/Math.PI,origin+lon*180/Math.PI]}
 function niceName(source){return source.replace(/^(?:\d+_)+/,'').replace(/_(region|polyline|text|point)$/i,'').replace(/_/g,' ')}
 function layerNames(hay){const rx=/[0-9A-Za-zА-Яа-яЁё .()\-]{1,96}_(?:region|polyline|text|point)\b/g;return[...new Set(hay.match(rx)||[])].map((source,index)=>({index,source,name:niceName(source),type:source.match(/_(region|polyline|text|point)$/i)?.[1]?.toLowerCase()||''})).slice(0,500)}
 function readExtent(view,zone,south){if(view.byteLength<2168||!zone)return null;const [xmin,ymin,xmax,ymax]=[2126,2138,2150,2162].map(o=>view.getFloat64(o,true));if(!(xmin>100000&&xmin<900000&&xmax>xmin&&ymin>0&&ymax>ymin))return null;const sw=utmToWgs84(xmin,ymin,zone,south),ne=utmToWgs84(xmax,ymax,zone,south);return{utm:{xmin,ymin,xmax,ymax},wgs84:{south:Math.min(sw[0],ne[0]),west:Math.min(sw[1],ne[1]),north:Math.max(sw[0],ne[0]),east:Math.max(sw[1],ne[1])}}}
 function storageBlocks(u8,layers){const pstg=findAscii(u8,'PSTG'),sqlite=findAscii(u8,'SQLite format 3');return pstg.map((offset,i)=>({index:i,offset,sqliteOffset:sqlite.find(x=>x>offset&&(i===pstg.length-1||x<pstg[i+1]))??null,layer:layers[i]?.source||null}))}
 function schemaHints(hay){return['FID_','gShape_','Лесничество','Леснич','КатЗащ','Nкварт','Nвыд','Площ','КатЗем','Бонитет','Тип_леса','Порода','Тон','ХозРасп'].filter(x=>hay.includes(x))}
 function lz4Raw(u8,start,maxOut=1024*1024){let i=start;const out=[];try{while(i<u8.length&&out.length<maxOut){const token=u8[i++];let lit=token>>>4;if(lit===15){let x;do{x=u8[i++];lit+=x}while(x===255)}if(i+lit>u8.length)throw 0;for(let k=0;k<lit;k++)out.push(u8[i++]);if(i>=u8.length)break;const off=u8[i]|u8[i+1]<<8;i+=2;if(!off||off>out.length)throw 0;let m=token&15;if(m===15){let x;do{x=u8[i++];m+=x}while(x===255)}m+=4;for(let k=0;k<m;k++){out.push(out[out.length-off]);if(out.length>=maxOut)break}}}catch(_){ }return{bytes:new Uint8Array(out),inputEnd:i,inputLength:i-start,outputLength:out.length}}
 function readU64LE(u8,o){if(o+8>u8.length)return null;let n=0;for(let b=0;b<8;b++)n+=u8[o+b]*2**(8*b);return Number.isSafeInteger(n)?n:null}
 function findSpatialHeader(bytes){for(let o=0;o<Math.min(32,bytes.length-17);o++){const version=bytes[o],a=u32(bytes,o+1),b=u32(bytes,o+5),c=u32(bytes,o+9),page=u32(bytes,o+13);if(version>0&&version<8&&a>0&&a===b&&b===c&&page>=512&&page<=65536&&(page&(page-1))===0)return{offset:o,version,objectCount:a,indexCount:b,shapeCount:c,pageSize:page,dataOffset:o+17,prefix:Array.from(bytes.slice(0,o))}}return null}
 function inspectPageStorage(logical){const p=findAscii(logical,'PSTG')[0];if(p==null)return null;return{offset:p,version:logical[p+4]??null,declaredPayloadBytes:readU64LE(logical,p+5),spatialBytesBeforePstg:p}}
 function readVarints(bytes,start,count=32){const out=[];let i=start;while(i<bytes.length&&out.length<count){const at=i;let v=0,shift=0;for(let k=0;k<10&&i<bytes.length;k++){const b=bytes[i++];v+=(b&127)*2**shift;if(b<128){out.push({offset:at,length:i-at,unsigned:v,zigzag:(v>>>1)^-(v&1)});break}shift+=7}}return out}
 function probeSpatialStream(u8,pstgOffsets){if(!pstgOffsets.length)return null;const first=pstgOffsets[0],from=Math.max(1024,first-180000);let hits=[];for(let s=from;s<first;s+=4){const p=lz4Raw(u8,s,256*1024);if(p.outputLength<32768||!findAscii(p.bytes,'PSTG').length||!findAscii(p.bytes,'SQLite format 3').length)continue;const h=findSpatialHeader(p.bytes);if(h&&h.offset<=16)hits.push({start:s,...p,header:h})}if(!hits.length)return null;let seed=hits.sort((a,b)=>b.outputLength-a.outputLength)[0],best=seed;for(let s=Math.max(from,seed.start-8);s<=seed.start+8;s++){const p=lz4Raw(u8,s,768*1024),h=findSpatialHeader(p.bytes);if(!h||h.offset>16||!findAscii(p.bytes,'PSTG').length||!findAscii(p.bytes,'SQLite format 3').length)continue;if(p.outputLength>best.outputLength)best={start:s,...p,header:h}}const ps=inspectPageStorage(best.bytes),h=best.header;return{start:best.start,inputEnd:best.inputEnd,compressedBytes:best.inputLength,logicalBytes:best.outputLength,header:h,pageStorage:ps,firstObjectProbe:{dataOffset:h.dataOffset,firstBytes:Array.from(best.bytes.slice(h.dataOffset,h.dataOffset+64)),varints:readVarints(best.bytes,h.dataOffset,32)}}}
 async function decode(file){const buf=await file.arrayBuffer(),u8=new Uint8Array(buf),view=new DataView(buf);if(asciiAt(u8,0,4)!=='CMF2')throw new Error('Это не CMF2');const a=new TextDecoder('utf-8',{fatal:false}).decode(u8),b=new TextDecoder('utf-16le',{fatal:false}).decode(u8),hay=a+'\n'+b,projection=(hay.match(/\+proj=utm[^\x00\r\n]{0,220}/)||[])[0]?.trim()||'',zone=Number((projection.match(/\+zone=(\d+)/)||[])[1])||null,south=/\+south\b/.test(projection),layers=layerNames(hay),blocks=storageBlocks(u8,layers);return{format:'CMF2',layers,projection:projection||'CMF2',zone,south,pstgBlocks:blocks.length,blocks,fields:schemaHints(hay),extent:readExtent(view,zone,south),spatialStream:probeSpatialStream(u8,blocks.map(x=>x.offset)),size:u8.length}}
 window.inspectCmf2=decode;window.SolinCmf2Lz4={decodeRaw:lz4Raw,findSpatialHeader,readVarints};
})();
