/* CMF2 reader: portable CarryMap SpatialBlock geometry decoding. */
(function(){
 const MOD32=4294967296;
 function asciiAt(u8,o,n){let s='';for(let i=o;i<Math.min(u8.length,o+n);i++)s+=String.fromCharCode(u8[i]);return s}
 function findAscii(u8,needle){const n=[...needle].map(c=>c.charCodeAt(0)),out=[];outer:for(let i=0;i<=u8.length-n.length;i++){for(let j=0;j<n.length;j++)if(u8[i+j]!==n[j])continue outer;out.push(i)}return out}
 function u32(u8,o){return o+4<=u8.length?(u8[o]|u8[o+1]<<8|u8[o+2]<<16|u8[o+3]<<24)>>>0:null}
 function i32(u8,o){const v=u32(u8,o);return v==null?null:(v>0x7fffffff?v-MOD32:v)}
 function utmToWgs84(easting,northing,zone,southHemisphere=false){const a=6378137,e2=.00669438,k0=.9996,ep=e2/(1-e2);if(southHemisphere)northing-=10000000;const M=northing/k0,mu=M/(a*(1-e2/4-3*e2*e2/64-5*Math.pow(e2,3)/256)),e1=(1-Math.sqrt(1-e2))/(1+Math.sqrt(1-e2)),p=mu+(3*e1/2-27*Math.pow(e1,3)/32)*Math.sin(2*mu)+(21*e1*e1/16-55*Math.pow(e1,4)/32)*Math.sin(4*mu)+(151*Math.pow(e1,3)/96)*Math.sin(6*mu),N=a/Math.sqrt(1-e2*Math.sin(p)**2),T=Math.tan(p)**2,C=ep*Math.cos(p)**2,R=a*(1-e2)/Math.pow(1-e2*Math.sin(p)**2,1.5),D=(easting-500000)/(N*k0),lat=p-(N*Math.tan(p)/R)*(D**2/2-(5+3*T+10*C-4*C*C-9*ep)*D**4/24+(61+90*T+298*C+45*T*T-252*ep-3*C*C)*D**6/720),lon=(D-(1+2*T+C)*D**3/6+(5-2*C+28*T-3*C*C+8*ep+24*T*T)*D**5/120)/Math.cos(p),origin=(zone-1)*6-180+3;return[lat*180/Math.PI,origin+lon*180/Math.PI]}
 function niceName(source){return source.replace(/^(?:\d+_)+/,'').replace(/_(region|polyline|text|point)$/i,'').replace(/_/g,' ')}
 function layerNames(hay){const rx=/\d+_\d+_[0-9A-Za-zА-Яа-яЁё _().-]{1,80}_(?:region|polyline|text|point)/g;return[...new Set(hay.match(rx)||[])].map((source,index)=>({index,source,name:niceName(source),type:source.match(/_(region|polyline|text|point)$/i)?.[1]?.toLowerCase()||''})).slice(0,500)}
 function extentObj(xmin,ymin,xmax,ymax,zone,south,offset){const sw=utmToWgs84(xmin,ymin,zone,south),ne=utmToWgs84(xmax,ymax,zone,south);return{offset,utm:{xmin,ymin,xmax,ymax},wgs84:{south:Math.min(sw[0],ne[0]),west:Math.min(sw[1],ne[1]),north:Math.max(sw[0],ne[0]),east:Math.max(sw[1],ne[1])}}}
 function plausibleExtent(xmin,ymin,xmax,ymax){if(![xmin,ymin,xmax,ymax].every(Number.isFinite))return false;if(!(xmin>100000&&xmin<900000&&xmax>xmin&&xmax<900000))return false;if(!(ymin>100000&&ymin<10000000&&ymax>ymin&&ymax<10000000))return false;const dx=xmax-xmin,dy=ymax-ymin;return dx>10&&dy>10&&dx<1000000&&dy<1000000}
 function readExtentCandidates(view,zone,south){if(!zone)return[];const out=[],seen=new Set();function add(o){if(o<0||o+32>view.byteLength)return;let vals;try{vals=[0,8,16,24].map(d=>view.getFloat64(o+d,true))}catch(_){return}if(!plausibleExtent(...vals))return;const key=vals.map(v=>Math.round(v*10)/10).join('|');if(seen.has(key))return;seen.add(key);out.push(extentObj(...vals,zone,south,o))}add(2126);for(let o=0;o+32<=view.byteLength;o+=2)add(o);out.sort((a,b)=>{const aa=(a.utm.xmax-a.utm.xmin)*(a.utm.ymax-a.utm.ymin),bb=(b.utm.xmax-b.utm.xmin)*(b.utm.ymax-b.utm.ymin);return aa-bb});return out.slice(0,100)}
 function storageBlocks(u8,layers){const pstg=findAscii(u8,'PSTG'),sqlite=findAscii(u8,'SQLite format 3');return pstg.map((offset,i)=>({index:i,offset,sqliteOffset:sqlite.find(x=>x>offset&&(i===pstg.length-1||x<pstg[i+1]))??null,layer:layers[i]?.source||null}))}
 function schemaHints(hay){return['FID_','gShape_','Лесничество','Леснич','КатЗащ','Nкварт','Nвыд','Площ','КатЗем','Бонитет','Тип_леса','Порода','Тон','ХозРасп'].filter(x=>hay.includes(x))}
 function lz4Raw(u8,start,maxOut=2*1024*1024){let i=start;const out=[];try{while(i<u8.length&&out.length<maxOut){const token=u8[i++];let lit=token>>>4;if(lit===15){let x;do{x=u8[i++];if(x==null)throw 0;lit+=x}while(x===255)}if(i+lit>u8.length)throw 0;for(let k=0;k<lit&&out.length<maxOut;k++)out.push(u8[i+k]);i+=lit;if(out.length>=maxOut)break;if(i>=u8.length)break;if(i+1>=u8.length)throw 0;const off=u8[i]|u8[i+1]<<8;i+=2;if(!off||off>out.length)throw 0;let m=token&15;if(m===15){let x;do{x=u8[i++];if(x==null)throw 0;m+=x}while(x===255)}m+=4;for(let k=0;k<m&&out.length<maxOut;k++)out.push(out[out.length-off])}}catch(_){ }return{bytes:new Uint8Array(out),inputEnd:i,inputLength:Math.max(0,i-start),outputLength:out.length}}
 function cleanHeader(bytes){if(bytes.length<17)return null;const version=bytes[0],a=u32(bytes,1),b=u32(bytes,5),c=u32(bytes,9),extra=u32(bytes,13);if(version<1||version>7||!a||a>1e6||a!==b||b!==c||extra==null||extra>1e6)return null;return{version,objectCount:a,bboxCount:b,shapeCount:c,extraPartCount:extra,dataOffset:17}}
 function likelyLz4SpatialStart(u8,s){if(s+2>=u8.length)return false;const lit=u8[s]>>>4;if(lit===0)return false;if(lit<15){const first=u8[s+1];return first>=1&&first<=7}return true}
 function ringArea(q){if(q.length<3)return 0;const x0=q[0][0],y0=q[0][1];let a=0;for(let i=0;i<q.length-1;i++)a+=(q[i][0]-x0)*(q[i+1][1]-y0)-(q[i+1][0]-x0)*(q[i][1]-y0);return a/2}
 function regionGeometry(rings){if(!rings.length)return null;const outerSign=Math.sign(ringArea(rings[0].q))||-1,polys=[];let cur=null;for(const r of rings){const sign=Math.sign(ringArea(r.q))||outerSign;if(!cur||sign===outerSign){cur=[r.ll];polys.push(cur)}else cur.push(r.ll)}return polys.length===1?{type:'Polygon',coordinates:polys[0]}:{type:'MultiPolygon',coordinates:polys}}
 function parseSpatialGeometry(bytes,layer,extent,zone,south){const h=cleanHeader(bytes);if(!h||!extent?.utm||!zone)return null;const n=h.objectCount;let o=h.dataOffset;const need=o+n*16+n*4+n*4+h.extraPartCount*4;if(need>bytes.length)return null;const boxes=[];for(let i=0;i<n;i++){const q=[u32(bytes,o),u32(bytes,o+4),u32(bytes,o+8),u32(bytes,o+12)];o+=16;if(q.some(v=>v==null)||q[0]>q[2]||q[1]>q[3])return null;boxes.push(q)}const vertexCounts=[];let totalVertices=0;for(let i=0;i<n;i++){const v=u32(bytes,o);o+=4;if(!v||v>1e7)return null;vertexCounts.push(v);totalVertices+=v}const partCounts=[];let multipartSlots=0;for(let i=0;i<n;i++){const p=u32(bytes,o);o+=4;if(!p||p>128)return null;partCounts.push(p);if(p>1)multipartSlots+=p}if(multipartSlots!==h.extraPartCount)return null;const extra=[];for(let i=0;i<h.extraPartCount;i++){const v=u32(bytes,o);o+=4;if(!v)return null;extra.push(v)}let ep=0;for(let i=0;i<n;i++)if(partCounts[i]>1){let sum=0;for(let k=0;k<partCounts[i];k++)sum+=extra[ep++];if(sum!==vertexCounts[i])return null}const e=extent.utm,dx=e.xmax-e.xmin,dy=e.ymax-e.ymin;let accX=0,accY=0,cp=o,extraPos=0;const features=[];for(let fi=0;fi<n;fi++){const vc=vertexCounts[fi],pc=partCounts[fi],lens=pc===1?[vc]:extra.slice(extraPos,extraPos+pc);if(pc>1)extraPos+=pc;const qbox=boxes[fi],rings=[];let used=0;for(const len of lens){const qring=[],ll=[];for(let j=0;j<len;j++){const sx=i32(bytes,cp),sy=i32(bytes,cp+4);cp+=8;accX=(accX+sx)%MOD32;if(accX<0)accX+=MOD32;accY=(accY+sy)%MOD32;if(accY<0)accY+=MOD32;if(accX<qbox[0]||accX>qbox[2]||accY<qbox[1]||accY>qbox[3])return null;const ux=e.xmin+accX/MOD32*dx,uy=e.ymin+accY/MOD32*dy,[lat,lon]=utmToWgs84(ux,uy,zone,south);qring.push([accX,accY]);ll.push([lon,lat]);used++}rings.push({q:qring,ll})}if(used!==vc)return null;let geometry;if(layer.type==='region')geometry=regionGeometry(rings);else if(layer.type==='polyline')geometry=rings.length===1?{type:'LineString',coordinates:rings[0].ll}:{type:'MultiLineString',coordinates:rings.map(r=>r.ll)};else continue;if(!geometry)return null;features.push({type:'Feature',properties:{CMF_LAYER:layer.source,CMF_NAME:layer.name,CMF_TYPE:layer.type,CMF_INDEX:fi+1},geometry})}return{index:layer.index,source:layer.source,name:layer.name,type:layer.type,count:features.length,header:h,totalVertices,geojson:{type:'FeatureCollection',features}}}
 function findGeometryLayer(u8,from,to,layer,extent,zone,south){if(!['region','polyline'].includes(layer.type))return null;for(let s=Math.max(0,from);s<Math.min(to,u8.length-17);s++){if(!likelyLz4SpatialStart(u8,s))continue;const peek=lz4Raw(u8,s,64);if(!cleanHeader(peek.bytes))continue;const full=lz4Raw(u8,s,4*1024*1024),parsed=parseSpatialGeometry(full.bytes,layer,extent,zone,south);if(parsed)return{...parsed,start:s,inputEnd:full.inputEnd,compressedBytes:full.inputLength,logicalBytes:full.outputLength}}return null}
 function windowsFor(blocks,size,preferred){const out=[];function add(from,to){from=Math.max(4,from);to=Math.min(size,to);if(to-from<17)return;if(!out.some(w=>w[0]===from&&w[1]===to))out.push([from,to])}if(preferred!=null&&blocks[preferred]){const to=blocks[preferred].offset,prev=preferred?blocks[preferred-1].offset+4:4;add(Math.max(prev,to-400000),to)}for(let i=0;i<blocks.length;i++){const to=blocks[i].offset,prev=i?blocks[i-1].offset+4:4;add(Math.max(prev,to-400000),to)}add(4,size);return out}
 function decodeWithExtent(u8,blocks,layers,extent,zone,south){const out=[],usedStarts=new Set();for(const layer of layers){if(!['region','polyline'].includes(layer.type))continue;let best=null;for(const [from,to] of windowsFor(blocks,u8.length,layer.index)){const g=findGeometryLayer(u8,from,to,layer,extent,zone,south);if(g&&!usedStarts.has(g.start)){best=g;break}}if(best){usedStarts.add(best.start);out.push(best)}}return out}
 function chooseGeometry(u8,blocks,layers,candidates,zone,south){let best={layers:[],extent:null,score:-1};for(const ext of candidates){const gs=decodeWithExtent(u8,blocks,layers,ext,zone,south);const score=gs.reduce((s,g)=>s+g.count*1000+(g.totalVertices||0),0);if(score>best.score)best={layers:gs,extent:ext,score};if(gs.length>=Math.max(2,layers.filter(l=>/region|polyline/.test(l.type)).length-1))break}return best}
 async function decode(file){const buf=await file.arrayBuffer(),u8=new Uint8Array(buf),view=new DataView(buf);if(u8.length<4||asciiAt(u8,0,4)!=='CMF2')throw new Error('Это не CMF2');const a=new TextDecoder('utf-8',{fatal:false}).decode(u8),b=new TextDecoder('utf-16le',{fatal:false}).decode(u8),hay=a+'\n'+b,projection=(hay.match(/\+proj=utm[^\x00\r\n]{0,220}/)||[])[0]?.trim()||'',zone=Number((projection.match(/\+zone=(\d+)/)||[])[1])||null,south=/\+south\b/.test(projection),layers=layerNames(hay),blocks=storageBlocks(u8,layers),extentCandidates=readExtentCandidates(view,zone,south),chosen=chooseGeometry(u8,blocks,layers,extentCandidates,zone,south),geometryLayers=chosen.layers,extent=chosen.extent||extentCandidates[0]||null;return{format:'CMF2',layers,projection:projection||'CMF2',zone,south,pstgBlocks:blocks.length,blocks,fields:schemaHints(hay),extent,extentCandidates:extentCandidates.length,geometryLayers,decodedFeatures:geometryLayers.reduce((s,x)=>s+x.count,0),decodedVertices:geometryLayers.reduce((s,x)=>s+(x.totalVertices||0),0),size:u8.length,decoderMode:'generic spatial scan'}}
 window.inspectCmf2=decode;window.SolinCmf2Lz4={decodeRaw:lz4Raw,cleanHeader,parseSpatialGeometry};
})();