function cmfReadProp(p,names){for(const n of names){if(p&&p[n]!==undefined&&p[n]!==null&&p[n]!=='')return p[n]}return null}
const cmfCarryOrder=[['Квартал',['Nкварт','NКВАРТ','KV','Квартал']],['Номер выдела',['Nвыд','NВЫД','VD','Выдел']],['Площадь, га',['Площ','PL','Площадь','Площ_геом']],['Категория защитности',['КатЗащ']],['Категория земли',['КатЗем']],['Бонитет',['Бонитет']],['Тип леса',['Тип_леса']],['Порода',['Порода']],['Тон',['Тон']],['Возраст, лет',['А_лет','Алет']],['Высота, м',['Н_м','H_м','H_m']],['Диаметр, см',['Д_см','D_см','D_cm']],['Полнота',['Полн_прижи']],['Запас, м³/га',['Запас_м3_г']],['Хозраспоряжение 1',['ХозРаспор1','ХозРасп']],['Процент 1',['Проц1']],['Хозраспоряжение 2',['ХозРаспор2']],['Процент 2',['Проц2']],['Ключ',['Ключ','KEY']],['Масштаб учёта',['МасУч']],['Обход',['Обход']],['FID',['FID','FID_','$OID$']]];
const cmfPretty={FID_:'FID',Лесничеств:'Лесничество',КатЗащ:'Категория защитности',Nкварт:'Квартал',Nвыд:'Номер выдела',Площ:'Площадь, га',Площ_геом:'Площадь, га',КатЗем:'Категория земли',Тип_леса:'Тип леса',А_лет:'Возраст, лет',Н_м:'Высота, м',Д_см:'Диаметр, см',Полн_прижи:'Полнота',Запас_м3_г:'Запас, м³/га',ХозРаспор1:'Хозраспоряжение 1',Проц1:'Процент 1',ХозРаспор2:'Хозраспоряжение 2',Проц2:'Процент 2',МасУч:'Масштаб учёта'};
function cmfInternalKey(k){return /^CMF_/i.test(String(k))||/^_/.test(String(k))}
function cmfStandKeys(feature){const p=feature?.properties||{};return{kv:cmfReadProp(p,['Nкварт','NКВАРТ','KV','Квартал']),vd:cmfReadProp(p,['Nвыд','NВЫД','VD','Выдел']),area:cmfReadProp(p,['Площ','PL','Площадь','Площ_геом'])}}
function cmfStandLabel(feature){const k=cmfStandKeys(feature);if(k.kv===null&&k.vd===null&&k.area===null)return'';const id=k.kv!==null&&k.vd!==null?`${k.kv}-${k.vd}`:(k.vd!==null?String(k.vd):(k.kv!==null?`Кв ${k.kv}`:''));const ar=k.area!==null?`${String(k.area).replace('.',',')} га`:'';return[id,ar].filter(Boolean).join('\n')}
function cmfObjectTitle(feature){const p=feature?.properties||{},k=cmfStandKeys(feature),src=String(p.CMF_LAYER||'');if(/выдпород|выдел/i.test(src)){if(k.kv!==null&&k.vd!==null)return`Выдел ${k.kv}-${k.vd}`;if(k.vd!==null)return`Выдел ${k.vd}`;return'Выдел'}if(/квпрос|кварт/i.test(src)&&k.kv!==null)return`Квартал ${k.kv}`;return p.CMF_NAME||'Объект CarryMap'}
function cmfStandPopup(feature,latlng){const p=feature?.properties||{},src=p.CMF_LAYER||'',title=cmfObjectTitle(feature),forest=cmfReadProp(p,['Лесничеств','Лесничество']),used=new Set(['CMF_LAYER','CMF_NAME','CMF_TYPE','CMF_INDEX','Лесничество','Лесничеств','ПородаПП']),attrRows=[];for(const [label,names] of cmfCarryOrder){const v=cmfReadProp(p,names);if(v!==null){names.forEach(x=>used.add(x));attrRows.push(`<div class="cmfAttr"><span>${esc(label)}</span><b>${esc(v)}</b></div>`)}}for(const [key,v] of Object.entries(p)){if(used.has(key)||cmfInternalKey(key)||v===null||v===''||/^g?shape_?$/i.test(key))continue;attrRows.push(`<div class="cmfAttr"><span>${esc(cmfPretty[key]||key)}</span><b>${esc(v)}</b></div>`)}if(!attrRows.length){const ar=cmfReadProp(p,['Площ','Площ_геом']);if(ar!==null)attrRows.push(`<div class="cmfAttr"><span>Площадь, га</span><b>${esc(ar)}</b></div>`);else attrRows.push('<div class="empty">Для этого объекта атрибуты не найдены</div>')}const coord=latlng?`<div class="cmfCoord">⌖ ${latlng.lat.toFixed(6)}°N, ${latlng.lng.toFixed(6)}°E</div>`:'';const subtitle=forest?`${forest} лесничество`:(String(src).replace(/^(?:\d+_)+/,'').replace(/_(region|polyline|text|point)$/i,'').replace(/_/g,' ')||'CarryMap');return `<div class="cmfCard"><div class="cmfCardHandle" id="cmfSheetHandle"></div>${coord}<div class="cmfCardTitle"><span class="cmfSwatch"></span><div><h3>${esc(title)}</h3><small>${esc(subtitle)}</small></div></div><div class="cmfSheetActions"><button onclick="cmfZoomSelected()">◇<span>Приблизить<br>к объекту</span></button><button onclick="cmfUseAsTarget()">⌁<span>Использовать<br>как цель</span></button></div>${attrRows.join('')}</div>`}
let cmfSheetLayer=null,cmfDragBound=false;
function bindCmfSheetDrag(sheet){if(!sheet||cmfDragBound)return;cmfDragBound=true;let startY=0,startBottom=0,dragging=false;const bottomPx=()=>parseFloat(getComputedStyle(sheet).bottom)||0;const down=e=>{const t=e.target;if(!(t?.id==='cmfSheetHandle'||t?.closest?.('.cmfCardHandle')))return;dragging=true;startY=e.clientY??e.touches?.[0]?.clientY??0;startBottom=bottomPx();sheet.classList.add('dragging');try{sheet.setPointerCapture?.(e.pointerId)}catch(_){}};const move=e=>{if(!dragging)return;const y=e.clientY??e.touches?.[0]?.clientY??0,dy=y-startY;sheet.style.bottom=`${Math.min(0,Math.max(-sheet.offsetHeight+86,startBottom-dy))}px`;e.preventDefault?.()};const up=()=>{if(!dragging)return;dragging=false;sheet.classList.remove('dragging');const hidden=-sheet.offsetHeight+86,b=bottomPx();sheet.style.bottom='';sheet.classList.remove('peek','open');if(b<hidden*.72){sheet.classList.add('peek')}else if(b<hidden*.28){sheet.classList.add('peek')}else sheet.classList.add('open')};sheet.addEventListener('pointerdown',down);sheet.addEventListener('pointermove',move);sheet.addEventListener('pointerup',up);sheet.addEventListener('pointercancel',up);sheet.addEventListener('touchstart',down,{passive:false});sheet.addEventListener('touchmove',move,{passive:false});sheet.addEventListener('touchend',up)}
function showCmfSheet(feature,latlng,layer){cmfSheetLayer=layer||cmfSheetLayer;window.__cmfSelectedLayer=layer||window.__cmfSelectedLayer;let sheet=document.getElementById('cmfSheet');if(!sheet){sheet=document.createElement('div');sheet.id='cmfSheet';sheet.className='cmfSheet';document.querySelector('#mapScreen .mapWrap')?.appendChild(sheet)}sheet.innerHTML=`<button class="cmfSheetClose" onclick="closeCmfSheet()">×</button>${cmfStandPopup(feature,latlng)}`;sheet.classList.remove('peek');sheet.classList.add('open');bindCmfSheetDrag(sheet);document.getElementById('cmfSheetHandle')?.addEventListener('click',()=>{if(sheet.classList.contains('peek')){sheet.classList.remove('peek');sheet.classList.add('open')}else{sheet.classList.remove('open');sheet.classList.add('peek')}})}
function closeCmfSheet(){const s=document.getElementById('cmfSheet');if(s){s.classList.remove('open','peek');s.style.bottom=''}window.__cmfSelectedLayer=null}
function cmfZoomSelected(){const l=window.__cmfSelectedLayer||cmfSheetLayer,b=l?.getBounds?.();if(b?.isValid())fieldMap.fitBounds(b,{padding:[40,40],maxZoom:17})}
function cmfUseAsTarget(){const l=window.__cmfSelectedLayer||cmfSheetLayer,b=l?.getBounds?.(),c=b?.isValid()?b.getCenter():null;if(!c)return toast('Не удалось определить центр объекта');fieldMap.setView(c,17);toast('Объект выбран как цель')}
function cmfStyle(layer){if(layer.id==='stands')return{color:'#21b445',weight:2.2,fillColor:'#21b445',fillOpacity:.04};if(layer.id==='water')return{color:'#3db7ff',weight:2.5,fillColor:'#3db7ff',fillOpacity:.3};if(layer.id==='roads')return{color:'#ff2b2b',weight:3.1,fillOpacity:0};if(layer.id==='quarterCuts'||layer.id==='landBorders')return{color:'#1677ff',weight:3,fillOpacity:0};return layer.type==='линии'?{color:'#d7e5dc',weight:1.8,fillOpacity:0}:{color:'#21b445',weight:1.6,fillOpacity:.04}}
window.loadAvailableGeoJsonLayers=async function(){for(const layer of cmf2Layers){try{const r=await fetch(`./map-layers/${layer.id}.geojson`,{cache:'no-store'});if(!r.ok)continue;const data=await r.json();layer.leaflet=L.geoJSON(data,{style:()=>cmfStyle(layer),pointToLayer:(f,ll)=>L.circleMarker(ll,{radius:4}),onEachFeature:(f,l)=>{if(layer.id==='stands'){const label=cmfStandLabel(f);if(label)l.bindTooltip(label,{permanent:true,direction:'center',className:'standPermanentLabel'});}l.on('click',e=>showCmfSheet(f,e.latlng,l))}});const cb=[...document.querySelectorAll('#mapLayerList input')][cmf2Layers.indexOf(layer)];if(cb&&cb.checked)layer.leaflet.addTo(fieldMap)}catch(e){console.warn(e)}}};