let fieldMap=null,baseGoogle=null,baseOSM=null,userMarker=null;
const cmf2Layers=[];
const importedMapLayers=[];
const cmfBounds=[[49.88939,58.94556],[50.34764,59.66651]];
function renderMapLayerList(){const box=document.getElementById('mapLayerList');if(!box)return;box.innerHTML=importedMapLayers.length?importedMapLayers.map((x,i)=>x.cmf2?`<div class="mapLayerRow"><span>◈</span><span>${escapeMapHtml(x.name)}<small>CMF2 · ${x.count} слоёв${x.projection?` · ${escapeMapHtml(x.projection)}`:''}</small></span></div>`:`<label class="mapLayerRow"><input type="checkbox" ${x.visible?'checked':''} onchange="toggleImportedLayer(${i},this.checked)"><span>${escapeMapHtml(x.name)}<small>${x.count} объектов${x.format?` · ${x.format}`:''}</small></span></label>`).join(''):`<div class="mapLayerRow"><span>＋</span><span>Откройте карту<small>CMF2 · KML · GeoJSON · GeoPackage</small></span></div>`}
function ensureMapFileUi(){if(document.getElementById('mapFileInput'))return;const toolbar=document.querySelector('#mapScreen .mapToolbar');if(toolbar){const b=document.createElement('button');b.className='mapMode';b.textContent='⌁ Открыть файл';b.onclick=openMapFilePicker;toolbar.appendChild(b)}const input=document.createElement('input');input.id='mapFileInput';input.type='file';input.multiple=true;input.style.display='none';input.onchange=()=>handleMapFiles(input);document.body.appendChild(input)}
function initFieldMap(){ensureMapFileUi();if(fieldMap||!window.L)return;fieldMap=L.map('fieldMap',{zoomControl:true,preferCanvas:true});baseGoogle=L.tileLayer('https://{s}.google.com/vt/lyrs=s&x={x}&y={y}&z={z}',{subdomains:['mt0','mt1','mt2','mt3'],maxZoom:21,attribution:'Спутниковые снимки Google'});baseOSM=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:20,attribution:'© OpenStreetMap'});baseGoogle.addTo(fieldMap);fieldMap.fitBounds(cmfBounds,{padding:[4,4]});renderMapLayerList();setTimeout(()=>fieldMap.invalidateSize(),150)}
function openMapScreen(){show('mapScreen');document.querySelectorAll('.sectionTab').forEach(x=>x.classList.toggle('active',x.dataset.s==='mapScreen'));initFieldMap();setTimeout(()=>fieldMap?.invalidateSize(),120)}
function setBaseMap(kind){if(!fieldMap)initFieldMap();if(!fieldMap)return;if(kind==='google'){if(fieldMap.hasLayer(baseOSM))fieldMap.removeLayer(baseOSM);if(!fieldMap.hasLayer(baseGoogle))baseGoogle.addTo(fieldMap)}else{if(fieldMap.hasLayer(baseGoogle))fieldMap.removeLayer(baseGoogle);if(!fieldMap.hasLayer(baseOSM))baseOSM.addTo(fieldMap)}document.getElementById('satBtn')?.classList.toggle('active',kind==='google');document.getElementById('osmBtn')?.classList.toggle('active',kind==='osm')}
function toggleMapLayers(){document.getElementById('mapLayerPanel')?.classList.toggle('hiddenPanel')}
function mapLocateMe(){if(!navigator.geolocation)return toast('GPS недоступен');navigator.geolocation.getCurrentPosition(p=>{const ll=[p.coords.latitude,p.coords.longitude];if(userMarker)userMarker.setLatLng(ll);else userMarker=L.circleMarker(ll,{radius:9,weight:3,fillOpacity:1}).addTo(fieldMap).bindPopup('Моё местоположение');fieldMap.setView(ll,16);userMarker.openPopup()},()=>toast('Не удалось получить GPS'),{enableHighAccuracy:true,timeout:10000})}
function openMapFilePicker(){document.getElementById('mapFileInput')?.click()}
function addGeoLayer(name,geo,key,format){if(!geo||geo.type!=='FeatureCollection')throw new Error('Нет векторных объектов');const group=L.geoJSON(geo,{style:styleImportedFeature,pointToLayer:(f,ll)=>L.circleMarker(ll,{radius:5,weight:2,fillOpacity:.8}),onEachFeature:bindImportedFeature}).addTo(fieldMap);const entry={key,name,layer:group,count:(geo.features||[]).length,visible:true,format};importedMapLayers.push(entry);return entry}
async function handleMapFiles(input){const files=[...(input?.files||[])];if(!files.length)return;if(!fieldMap)initFieldMap();let added=0,lastBounds=null;for(const file of files){try{const baseKey=`${file.name}|${file.size}|${file.lastModified}`;if(importedMapLayers.some(x=>x.fileKey===baseKey||x.key===baseKey))continue;if(/\.cmf2$/i.test(file.name)){const info=await inspectCmf2(file);const entry={key:baseKey,fileKey:baseKey,name:file.name,cmf2:true,count:info.layers.length,projection:info.projection,visible:true,info};if(info.extent?.wgs84){const e=info.extent.wgs84,b=[[e.south,e.west],[e.north,e.east]];entry.layer=L.rectangle(b,{weight:2,fillOpacity:0,dashArray:'7 6',interactive:false}).addTo(fieldMap);fieldMap.fitBounds(b,{padding:[12,12]})}importedMapLayers.push(entry);toast(`CMF2: найдено ${info.layers.length} слоёв`);continue}if(/\.gpkg$/i.test(file.name)){const pack=await openGeoPackageFile(file);if(!pack.layers.length)throw new Error('В GeoPackage нет векторных таблиц');for(const t of pack.layers){const e=addGeoLayer(`${file.name} › ${t.name}`,t.geojson,`${baseKey}|${t.name}`,'GPKG');e.fileKey=baseKey;added+=e.count;const b=e.layer.getBounds();if(b?.isValid())lastBounds=b}toast(`GeoPackage открыт: ${pack.layers.length} слоёв`);continue}const text=await file.text();let geo,format;if(/\.kml$/i.test(file.name)){geo=kmlToGeoJSON(text);format='KML'}else if(/\.(geojson|json)$/i.test(file.name)){geo=JSON.parse(text);format='GeoJSON'}else throw new Error('Формат распознать не удалось');const e=addGeoLayer(file.name,geo,baseKey,format);e.fileKey=baseKey;added+=e.count;const b=e.layer.getBounds();if(b?.isValid())lastBounds=b}catch(e){console.error(e);toast(`${file.name}: ${e.message||'не удалось открыть'}`)}}renderMapLayerList();if(lastBounds?.isValid())fieldMap.fitBounds(lastBounds,{padding:[18,18]});if(added)toast(`Открыто объектов: ${added}`);if(input)input.value=''}
function toggleImportedLayer(index,on){const x=importedMapLayers[index];if(!x||!fieldMap||x.cmf2)return;x.visible=on;if(on){if(!fieldMap.hasLayer(x.layer))x.layer.addTo(fieldMap)}else if(fieldMap.hasLayer(x.layer))fieldMap.removeLayer(x.layer)}
function styleImportedFeature(f){const t=f?.geometry?.type||'';if(t.includes('Line'))return{weight:3,opacity:.95};if(t.includes('Polygon'))return{weight:2,fillOpacity:.18};return{weight:2,fillOpacity:.8}}
function bindImportedFeature(feature,layer){layer.on('click',()=>{if(typeof showCmfSheet==='function')showCmfSheet(feature);else{const p=feature?.properties||{};layer.bindPopup(Object.entries(p).slice(0,20).map(([k,v])=>`<b>${escapeMapHtml(k)}</b>: ${escapeMapHtml(v)}`).join('<br>')||'Объект').openPopup()}})}
function escapeMapHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function kmlToGeoJSON(text){const xml=new DOMParser().parseFromString(text,'text/xml');if(xml.querySelector('parsererror'))throw new Error('Повреждённый KML');const features=[];xml.querySelectorAll('Placemark').forEach(pm=>{const props={};const name=pm.querySelector(':scope > name')?.textContent?.trim();if(name)props.name=name;pm.querySelectorAll('ExtendedData Data').forEach(d=>{const k=d.getAttribute('name'),v=d.querySelector('value')?.textContent?.trim();if(k)props[k]=v??''});pm.querySelectorAll('ExtendedData SimpleData').forEach(d=>{const k=d.getAttribute('name');if(k)props[k]=d.textContent?.trim()||''});const geoms=[];pm.querySelectorAll('Point,LineString,Polygon').forEach(el=>{if(el.closest('Placemark')===pm){const g=kmlGeometry(el);if(g)geoms.push(g)}});if(geoms.length)features.push({type:'Feature',properties:props,geometry:geoms.length===1?geoms[0]:{type:'GeometryCollection',geometries:geoms}})});return{type:'FeatureCollection',features}}
function kmlGeometry(el){const tag=el.localName;if(tag==='Point'){const c=parseKmlCoords(el.querySelector('coordinates')?.textContent);return c.length?{type:'Point',coordinates:c[0]}:null}if(tag==='LineString'){const c=parseKmlCoords(el.querySelector('coordinates')?.textContent);return c.length>1?{type:'LineString',coordinates:c}:null}if(tag==='Polygon'){const rings=[];el.querySelectorAll('outerBoundaryIs LinearRing coordinates, innerBoundaryIs LinearRing coordinates').forEach(n=>{const c=parseKmlCoords(n.textContent);if(c.length>2)rings.push(c)});return rings.length?{type:'Polygon',coordinates:rings}:null}return null}
function parseKmlCoords(s){return String(s||'').trim().split(/\s+/).map(x=>x.split(',').slice(0,3).map(Number)).filter(a=>a.length>=2&&Number.isFinite(a[0])&&Number.isFinite(a[1]))}
