let fieldMap=null,baseGoogle=null,baseOSM=null,userMarker=null;
const cmf2Layers=[
 {id:'stands',name:'Выделы / породы',source:'4_2_ВыдПород_region',type:'полигоны'},
 {id:'water',name:'Воды',source:'4_2_Воды_region',type:'полигоны'},
 {id:'banks',name:'Берега',source:'4_2_Берега_polyline',type:'линии'},
 {id:'roads',name:'Дороги',source:'4_2_Дороги_polyline',type:'линии'},
 {id:'quarterCuts',name:'Квартальные просеки',source:'4_2_КвПрос_polyline',type:'линии'},
 {id:'symbols',name:'Условные знаки',source:'4_2_УслЗн_region',type:'полигоны'},
 {id:'landBorders',name:'Границы земель',source:'4_2_ГрЗем_polyline',type:'линии'},
 {id:'labels',name:'Текст',source:'4_2_Текст_text',type:'подписи'},
 {id:'neighbors',name:'Смежества',source:'4_2_Смежества_text',type:'подписи'},
 {id:'quarterNumbers',name:'Номера кварталов',source:'4_2_НомКв_text',type:'подписи'}
];
const importedMapLayers=[];
const cmfBounds=[[49.88939,58.94556],[50.34764,59.66651]];
function renderMapLayerList(){const box=document.getElementById('mapLayerList');if(!box)return;const cmf=cmf2Layers.map((x,i)=>`<label class="mapLayerRow"><input type="checkbox" ${i===0||x.id==='quarterCuts'||x.id==='quarterNumbers'?'checked':''} onchange="toggleCmfLayer('${x.id}',this.checked)"><span>${x.name}<small>${x.source}</small></span></label>`).join('');const imp=importedMapLayers.length?`<div class="mapLayerTitle" style="margin-top:10px"><b>Открытые файлы</b><small>Локальные KML / GeoJSON</small></div>`+importedMapLayers.map((x,i)=>`<label class="mapLayerRow"><input type="checkbox" ${x.visible?'checked':''} onchange="toggleImportedLayer(${i},this.checked)"><span>${escapeMapHtml(x.name)}<small>${x.count} объектов</small></span></label>`).join(''):'';box.innerHTML=cmf+imp}
function ensureMapFileUi(){if(document.getElementById('mapFileInput'))return;const toolbar=document.querySelector('#mapScreen .mapToolbar');if(toolbar){const b=document.createElement('button');b.className='mapMode';b.textContent='⌁ Открыть файл';b.onclick=openMapFilePicker;toolbar.appendChild(b)}const input=document.createElement('input');input.id='mapFileInput';input.type='file';input.accept='.kml,.geojson,.json,application/vnd.google-earth.kml+xml,application/geo+json';input.multiple=true;input.style.display='none';input.onchange=()=>handleMapFiles(input);document.body.appendChild(input)}
function initFieldMap(){ensureMapFileUi();if(fieldMap||!window.L)return;fieldMap=L.map('fieldMap',{zoomControl:true,preferCanvas:true});baseGoogle=L.tileLayer('https://{s}.google.com/vt/lyrs=s&x={x}&y={y}&z={z}',{subdomains:['mt0','mt1','mt2','mt3'],maxZoom:21,attribution:'Спутниковые снимки Google'});baseOSM=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:20,attribution:'© OpenStreetMap'});baseGoogle.addTo(fieldMap);fieldMap.fitBounds(cmfBounds,{padding:[4,4]});renderMapLayerList();loadAvailableGeoJsonLayers();setTimeout(()=>fieldMap.invalidateSize(),150)}
async function loadAvailableGeoJsonLayers(){for(const layer of cmf2Layers){try{const r=await fetch(`./map-layers/${layer.id}.geojson`,{cache:'no-store'});if(!r.ok)continue;const data=await r.json();layer.leaflet=L.geoJSON(data,{style:()=>({weight:2,fillOpacity:.16}),pointToLayer:(f,ll)=>L.circleMarker(ll,{radius:4}),onEachFeature:bindImportedFeature});const cb=[...document.querySelectorAll('#mapLayerList input')][cmf2Layers.indexOf(layer)];if(cb?.checked)layer.leaflet.addTo(fieldMap)}catch(e){console.warn(e)}}}
function toggleCmfLayer(id,on){const x=cmf2Layers.find(v=>v.id===id);if(!x)return;if(x.leaflet){if(on)x.leaflet.addTo(fieldMap);else fieldMap.removeLayer(x.leaflet)}else if(on)toast(`${x.name}: геометрия CMF2 ещё не извлечена`)}
function openMapScreen(){show('mapScreen');document.querySelectorAll('.sectionTab').forEach(x=>x.classList.toggle('active',x.dataset.s==='mapScreen'));initFieldMap();setTimeout(()=>fieldMap?.invalidateSize(),120)}
function setBaseMap(kind){if(!fieldMap)initFieldMap();if(!fieldMap)return;if(kind==='google'){if(fieldMap.hasLayer(baseOSM))fieldMap.removeLayer(baseOSM);if(!fieldMap.hasLayer(baseGoogle))baseGoogle.addTo(fieldMap)}else{if(fieldMap.hasLayer(baseGoogle))fieldMap.removeLayer(baseGoogle);if(!fieldMap.hasLayer(baseOSM))baseOSM.addTo(fieldMap)}document.getElementById('satBtn')?.classList.toggle('active',kind==='google');document.getElementById('osmBtn')?.classList.toggle('active',kind==='osm')}
function toggleMapLayers(){document.getElementById('mapLayerPanel')?.classList.toggle('hiddenPanel')}
function mapLocateMe(){if(!navigator.geolocation)return toast('GPS недоступен');navigator.geolocation.getCurrentPosition(p=>{const ll=[p.coords.latitude,p.coords.longitude];if(!fieldMap)initFieldMap();if(userMarker)userMarker.setLatLng(ll);else userMarker=L.circleMarker(ll,{radius:9,weight:3,fillOpacity:1}).addTo(fieldMap).bindPopup('Моё местоположение');fieldMap.setView(ll,16);userMarker.openPopup()},()=>toast('Не удалось получить GPS'),{enableHighAccuracy:true,timeout:10000})}
function openMapFilePicker(){document.getElementById('mapFileInput')?.click()}
async function handleMapFiles(input){const files=[...(input?.files||[])];if(!files.length)return;if(!fieldMap)initFieldMap();let added=0;for(const file of files){try{const text=await file.text();let geo;if(/\.kml$/i.test(file.name))geo=kmlToGeoJSON(text);else if(/\.(geojson|json)$/i.test(file.name))geo=JSON.parse(text);else throw new Error('Поддерживаются KML и GeoJSON');if(!geo||geo.type!=='FeatureCollection')throw new Error('В файле нет FeatureCollection');const group=L.geoJSON(geo,{style:f=>styleImportedFeature(f),pointToLayer:(f,ll)=>L.circleMarker(ll,{radius:5,weight:2,fillOpacity:.8}),onEachFeature:bindImportedFeature});group.addTo(fieldMap);const entry={name:file.name,layer:group,count:(geo.features||[]).length,visible:true};importedMapLayers.push(entry);added+=entry.count;const b=group.getBounds();if(b?.isValid())fieldMap.fitBounds(b,{padding:[18,18]})}catch(e){console.error(e);toast(`${file.name}: ${e.message||'не удалось открыть'}`)}}renderMapLayerList();if(added)toast(`Открыто объектов: ${added}`);if(input)input.value=''}
function toggleImportedLayer(index,on){const x=importedMapLayers[index];if(!x||!fieldMap)return;x.visible=on;if(on){if(!fieldMap.hasLayer(x.layer))x.layer.addTo(fieldMap)}else if(fieldMap.hasLayer(x.layer))fieldMap.removeLayer(x.layer)}
function styleImportedFeature(f){const t=f?.geometry?.type||'';if(t.includes('Line'))return{weight:3,opacity:.95};if(t.includes('Polygon'))return{weight:2,fillOpacity:.18};return{weight:2,fillOpacity:.8}}
function bindImportedFeature(feature,layer){layer.on('click',()=>{if(typeof showCmfSheet==='function')showCmfSheet(feature);else{const p=feature?.properties||{};layer.bindPopup(Object.entries(p).slice(0,12).map(([k,v])=>`<b>${escapeMapHtml(k)}</b>: ${escapeMapHtml(v)}`).join('<br>')||'Объект').openPopup()}})}
function escapeMapHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function kmlToGeoJSON(text){const xml=new DOMParser().parseFromString(text,'text/xml');if(xml.querySelector('parsererror'))throw new Error('Повреждённый KML');const features=[];xml.querySelectorAll('Placemark').forEach(pm=>{const props={};const name=pm.querySelector(':scope > name')?.textContent?.trim();const desc=pm.querySelector(':scope > description')?.textContent?.trim();if(name)props.name=name;if(desc)props.description=desc;pm.querySelectorAll('ExtendedData Data').forEach(d=>{const k=d.getAttribute('name');const v=d.querySelector('value')?.textContent?.trim();if(k)props[k]=v??''});pm.querySelectorAll('ExtendedData SimpleData').forEach(d=>{const k=d.getAttribute('name');if(k)props[k]=d.textContent?.trim()||''});const geoms=[];pm.querySelectorAll('Point,LineString,Polygon').forEach(el=>{if(el.closest('Placemark')!==pm)return;const g=kmlGeometry(el);if(g)geoms.push(g)});if(!geoms.length)return;const geometry=geoms.length===1?geoms[0]:{type:'GeometryCollection',geometries:geoms};features.push({type:'Feature',properties:props,geometry})});return{type:'FeatureCollection',features}}
function kmlGeometry(el){const tag=el.localName;if(tag==='Point'){const c=parseKmlCoords(el.querySelector('coordinates')?.textContent);return c.length?{type:'Point',coordinates:c[0]}:null}if(tag==='LineString'){const c=parseKmlCoords(el.querySelector('coordinates')?.textContent);return c.length>1?{type:'LineString',coordinates:c}:null}if(tag==='Polygon'){const rings=[];el.querySelectorAll('outerBoundaryIs LinearRing coordinates, innerBoundaryIs LinearRing coordinates').forEach(n=>{const c=parseKmlCoords(n.textContent);if(c.length>2)rings.push(c)});return rings.length?{type:'Polygon',coordinates:rings}:null}return null}
function parseKmlCoords(s){return String(s||'').trim().split(/\s+/).map(x=>x.split(',').slice(0,3).map(Number)).filter(a=>a.length>=2&&Number.isFinite(a[0])&&Number.isFinite(a[1]))}
